---
title: "R Notebook"
output: html_notebook
---

---
title: "R Notebook"
output: html_notebook
---

#load libraries

library(readr)
library(tidyverse)
library(dplyr)
library(lubridate)
library(tidyr)
library(kableExtra)
library(knitr)
library(fastDummies)

CLEANING AND PROCESSING THE DATA

#Loading original datast
tsa_claims <- read_csv("tsa_claims.csv")

#exploring data summary, structure and types

str(tsa_claims)
summary(tsa_claims)


#Renaming the non-standard variables with standard names

TSA_claims <- tsa_claims %>%
  rename(Claim_Number =  `Claim Number`,
         Date_Received = `Date Received`,
         Incident_Date = `Incident Date`,
         Airport_Code = `Airport Code`,
         Airport_Name = `Airport Name`,
         Airline_Name = `Airline Name`,
         Claim_Type = `Claim Type`,
         Claim_Site = `Claim Site`,
         Claim_Amount = `Claim Amount`,
         Close_Amount = `Close Amount`)
TSA_claims

#Remove unwanted characters from specific variables, specifically Claim_Amount & Close_Amount

TSA_claims <- TSA_claims %>%
  mutate_if(is.character, str_replace_all, pattern = '[$]', replacement = '') %>%
  mutate_if(is.character, str_replace_all, pattern = '[;]', replacement = '') %>%
  #Convert data type for specific variables
  mutate(
         Date_Received = dmy(Date_Received),
         Incident_Date = mdy(Incident_Date),
         Airport_Code = as_factor(Airport_Code),
         Claim_Type = as_factor(Claim_Type),
         Claim_Site = as_factor(Claim_Site),
         Claim_Amount = as.double(Claim_Amount),
         Status = as_factor(Status),
         Close_Amount = as.double(Close_Amount),
         Disposition = as_factor(Disposition)
         )

#Verifying conversion to TSA_claims tbl

str(TSA_claims)
summary(TSA_claims)

Columns: Discusss exploration of the following variables
1.  Claim_Number - NA
2.  Date_Received - This represents the dates when claims where received by the TSA.
3.  Incident_Date - This is the date the actual incident ocurred that lead to a claim
    Explore possible relationships between the time an incident and when a claim is filed for said incident
4. Airport_Code - FAA designated code for a specific airport
5. Airport_Name - Name of the Airport
    Verify that all listed Airport codes have corresponding Airport names. We will attempt to convert airport codes to dummy       variables and apply categorical variable imputation methods to see if we can address NAs in these columns
6.  Airline_Name
7.  Claim_Type - Type of claim
    Convert to dummy variables and apply imputation techniques to address NAs
8.  Claim_Site - where in the Airport, the incident may have occurred
    Convert to dummy variables and apply imputation techniques to address NAs
9.  Item - Items for which a claim is being made
10. Claim_Amount - amount being requested by the claimant
    Apply imputation techniques to address NAs
11. Status - preliminary status of claim
    Convert to dummy variables and apply imputation techniques to address NAs
12. Close_Amount - amount that was granted by the TSA
    Apply imputation techniques to address NAs
13. Disposition - Final decision
    Response variable

Inspecting NAs in all columns

na_tsa <- TSA_tbl %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.)))) 

t(na_tsa)


DATE COLUMNS

Approximately 1600 observations in the dataset have Incident Dates that occus after the date the claim was received (Date_Received). For the purposes of this project, we will modify the Incident_Date of those observations using the duration period derived and adjusting them to precede the Date received

TSA_claims %>%
  select(Date_Received, Incident_Date) %>%
  mutate(Duration = Date_Received - Incident_Date) %>%
  mutate(New_Incident_Date = ifelse(Duration < 0, Date_Received + Duration, as.Date(Incident_Date))) %>%
  mutate(New_Incident_Date = as.Date(New_Incident_Date, origin = "1970-01-01"))


*3/22/2020*

##Exploring the Relationship between "Status" and "Disposition" in addressing NAs for Claim_Amount, Close_Amount & Disposition

options(scipen = 999) #Remove scientific notations for large numbers

#Count of the different status levels
TSA_claims %>%
  count(Status)

#There are just 8 missing values in the Status variable
TSA_claims %>%
  select(Status) %>%
  filter(is.na(Status))

#Filter observations with Approved status and Claim/Close_Amount is NA
#133 observations in which the status and disposition are both approved but the Closed_Amount is NA
#213 observations in which the status and disposition are both approved but the Claim_Amount is NA
TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Approved",
         is.na(Close_Amount))

TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Approved",
         !is.na(Claim_Amount)) %>%
  arrange(desc(Claim_Amount))


#Filter observations with Settled status and Claim/Close_Amount is NA
#0 observations in which the status and disposition are both settled but the Closed_Amount is NA
#214 observations in which the status and disposition are both settled but the Claim_Amount is NA
TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Settled",
         is.na(Close_Amount)) 

TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Settled",
         is.na(Claim_Amount)) 


#Filter observations with Cancelled status and Claim/Close_Amount is NA
#2863 observations in which the status is Cancelled but the Closed_Amount is NA. All Disposition is also NA
#1113 observations in which the status is Cancelled but the Claim_Amount is NA. All Disposition is also NA and Close_Amount is either NA or 0
TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Canceled",
         is.na(Close_Amount))

TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Canceled",
         is.na(Claim_Amount))


#Filter observations with Denied status and Claim/Close_Amount is NA
#1277 observations in which the status and disposition are both denied but the Close_Amount is NA
#331 observations in which the status and disposition are both denied but the Claim_Amount is NA

TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Denied",
         is.na(Close_Amount))

TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Denied",
         !is.na(Claim_Amount)) %>%
  arrange(desc(Claim_Amount))

#Filter observations with Insufficient status and Claim/Close_Amount is NA
#5381 observations in which the status is Insufficient but the Close_Amount is NA. All Disposition is also NA
#2096 observations in which the status is Insufficient but the Claim_Amount is NA. All Disposition is also NA or Deny
TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Insufficient one of the following items required: sum certain statement of fact signature location of incident and date.",
         is.na(Close_Amount))

TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Insufficient one of the following items required: sum certain statement of fact signature location of incident and date.",
         is.na(Claim_Amount))

#In litigation
#108 observations in which the status is In Litigation and Close_Amount is NA. Grouped by disposition 
#0 observations in which the status is In Litigation and Claim_Amount is NA.
TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "In litigation",
         is.na(Close_Amount)) %>%
  group_by(Disposition) %>%
  arrange(Disposition)

TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "In litigation",
         is.na(Claim_Amount))

#Closed as a contractor claim - Claims were Airport contractors erroneously file claims as passengers
#42 observations in which the status is "Closed as a contractor claim" and Close_Amount is NA. 
#57 observations in which the status is "Closed as a contractor claim" and Claim_Amount is NA.
TSA_claims %>%
  select(Item, Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Closed as a contractor claim",
         is.na(Close_Amount))

TSA_claims %>%
  select(Status, Claim_Amount, Close_Amount, Disposition) %>%
  filter(Status == "Closed as a contractor claim",
         is.na(Claim_Amount))
   
   
*CA: 3-29-2020*
#Clean up the values in Status:
#Code "Approved" as "Approve in Full"
#Code "Denied" as "Deny"
#Code "Settled" as "Settle"
TSA_claims <- TSA_claims %>%
  mutate(Status = replace(Status, Status == 'Approved', 'Approve in Full'),
         Status = replace(Status, Status == 'Denied', 'Deny'),
         Status = replace(Status, Status == 'Settled', 'Settle'))

